// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent_hooks.dart';
import 'api/git.dart';
import 'api/workspace_files.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AgentHookEventBatchDto>
  dco_decode_StreamSink_agent_hook_event_batch_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<WorkspaceExplorerWatchBatch>
  dco_decode_StreamSink_workspace_explorer_watch_batch_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentHookEndpointDto dco_decode_agent_hook_endpoint_dto(dynamic raw);

  @protected
  AgentHookEventBatchDto dco_decode_agent_hook_event_batch_dto(dynamic raw);

  @protected
  AgentHookEventDto dco_decode_agent_hook_event_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  WorkspaceExplorerDirectoryChildren
  dco_decode_box_autoadd_workspace_explorer_directory_children(dynamic raw);

  @protected
  WorkspaceExplorerWatcherHandle
  dco_decode_box_autoadd_workspace_explorer_watcher_handle(dynamic raw);

  @protected
  WorkspaceFileGitStatus dco_decode_box_autoadd_workspace_file_git_status(
    dynamic raw,
  );

  @protected
  GitError dco_decode_git_error(dynamic raw);

  @protected
  GitErrorKind dco_decode_git_error_kind(dynamic raw);

  @protected
  GitWorktreeEntry dco_decode_git_worktree_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AgentHookEventDto> dco_decode_list_agent_hook_event_dto(dynamic raw);

  @protected
  List<GitWorktreeEntry> dco_decode_list_git_worktree_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<WorkspaceExplorerDirectoryChildren>
  dco_decode_list_workspace_explorer_directory_children(dynamic raw);

  @protected
  List<WorkspaceExplorerEntryBinding>
  dco_decode_list_workspace_explorer_entry_binding(dynamic raw);

  @protected
  List<WorkspaceExplorerTreeNode> dco_decode_list_workspace_explorer_tree_node(
    dynamic raw,
  );

  @protected
  List<WorkspaceFileEntry> dco_decode_list_workspace_file_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  WorkspaceExplorerDirectoryChildren?
  dco_decode_opt_box_autoadd_workspace_explorer_directory_children(dynamic raw);

  @protected
  WorkspaceFileGitStatus? dco_decode_opt_box_autoadd_workspace_file_git_status(
    dynamic raw,
  );

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceEditorTextFile dco_decode_workspace_editor_text_file(dynamic raw);

  @protected
  WorkspaceExplorerDirectoryChildren
  dco_decode_workspace_explorer_directory_children(dynamic raw);

  @protected
  WorkspaceExplorerEntryBinding dco_decode_workspace_explorer_entry_binding(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerTreeNode dco_decode_workspace_explorer_tree_node(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerTreeNodeKind dco_decode_workspace_explorer_tree_node_kind(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerTreeProjection dco_decode_workspace_explorer_tree_projection(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerWatchBatch dco_decode_workspace_explorer_watch_batch(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerWatcherHandle dco_decode_workspace_explorer_watcher_handle(
    dynamic raw,
  );

  @protected
  WorkspaceFileEntry dco_decode_workspace_file_entry(dynamic raw);

  @protected
  WorkspaceFileError dco_decode_workspace_file_error(dynamic raw);

  @protected
  WorkspaceFileErrorKind dco_decode_workspace_file_error_kind(dynamic raw);

  @protected
  WorkspaceFileGitStatus dco_decode_workspace_file_git_status(dynamic raw);

  @protected
  WorkspaceFileKind dco_decode_workspace_file_kind(dynamic raw);

  @protected
  WorkspaceTextFile dco_decode_workspace_text_file(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AgentHookEventBatchDto>
  sse_decode_StreamSink_agent_hook_event_batch_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WorkspaceExplorerWatchBatch>
  sse_decode_StreamSink_workspace_explorer_watch_batch_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentHookEndpointDto sse_decode_agent_hook_endpoint_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentHookEventBatchDto sse_decode_agent_hook_event_batch_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentHookEventDto sse_decode_agent_hook_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  WorkspaceExplorerDirectoryChildren
  sse_decode_box_autoadd_workspace_explorer_directory_children(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerWatcherHandle
  sse_decode_box_autoadd_workspace_explorer_watcher_handle(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileGitStatus sse_decode_box_autoadd_workspace_file_git_status(
    SseDeserializer deserializer,
  );

  @protected
  GitError sse_decode_git_error(SseDeserializer deserializer);

  @protected
  GitErrorKind sse_decode_git_error_kind(SseDeserializer deserializer);

  @protected
  GitWorktreeEntry sse_decode_git_worktree_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AgentHookEventDto> sse_decode_list_agent_hook_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GitWorktreeEntry> sse_decode_list_git_worktree_entry(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<WorkspaceExplorerDirectoryChildren>
  sse_decode_list_workspace_explorer_directory_children(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceExplorerEntryBinding>
  sse_decode_list_workspace_explorer_entry_binding(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceExplorerTreeNode> sse_decode_list_workspace_explorer_tree_node(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceFileEntry> sse_decode_list_workspace_file_entry(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  WorkspaceExplorerDirectoryChildren?
  sse_decode_opt_box_autoadd_workspace_explorer_directory_children(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileGitStatus? sse_decode_opt_box_autoadd_workspace_file_git_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceEditorTextFile sse_decode_workspace_editor_text_file(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerDirectoryChildren
  sse_decode_workspace_explorer_directory_children(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerEntryBinding sse_decode_workspace_explorer_entry_binding(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerTreeNode sse_decode_workspace_explorer_tree_node(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerTreeNodeKind sse_decode_workspace_explorer_tree_node_kind(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerTreeProjection sse_decode_workspace_explorer_tree_projection(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerWatchBatch sse_decode_workspace_explorer_watch_batch(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerWatcherHandle sse_decode_workspace_explorer_watcher_handle(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileEntry sse_decode_workspace_file_entry(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileError sse_decode_workspace_file_error(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileErrorKind sse_decode_workspace_file_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileGitStatus sse_decode_workspace_file_git_status(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileKind sse_decode_workspace_file_kind(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceTextFile sse_decode_workspace_text_file(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_agent_hook_event_batch_dto_Sse(
    RustStreamSink<AgentHookEventBatchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_workspace_explorer_watch_batch_Sse(
    RustStreamSink<WorkspaceExplorerWatchBatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_hook_endpoint_dto(
    AgentHookEndpointDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_hook_event_batch_dto(
    AgentHookEventBatchDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_hook_event_dto(
    AgentHookEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_workspace_explorer_directory_children(
    WorkspaceExplorerDirectoryChildren self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_explorer_watcher_handle(
    WorkspaceExplorerWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_file_git_status(
    WorkspaceFileGitStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_error(GitError self, SseSerializer serializer);

  @protected
  void sse_encode_git_error_kind(GitErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_git_worktree_entry(
    GitWorktreeEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agent_hook_event_dto(
    List<AgentHookEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_worktree_entry(
    List<GitWorktreeEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_explorer_directory_children(
    List<WorkspaceExplorerDirectoryChildren> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_explorer_entry_binding(
    List<WorkspaceExplorerEntryBinding> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_explorer_tree_node(
    List<WorkspaceExplorerTreeNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_file_entry(
    List<WorkspaceFileEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_workspace_explorer_directory_children(
    WorkspaceExplorerDirectoryChildren? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_workspace_file_git_status(
    WorkspaceFileGitStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_editor_text_file(
    WorkspaceEditorTextFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_directory_children(
    WorkspaceExplorerDirectoryChildren self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_entry_binding(
    WorkspaceExplorerEntryBinding self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_tree_node(
    WorkspaceExplorerTreeNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_tree_node_kind(
    WorkspaceExplorerTreeNodeKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_tree_projection(
    WorkspaceExplorerTreeProjection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_watch_batch(
    WorkspaceExplorerWatchBatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_watcher_handle(
    WorkspaceExplorerWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_entry(
    WorkspaceFileEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_error(
    WorkspaceFileError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_error_kind(
    WorkspaceFileErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_git_status(
    WorkspaceFileGitStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_kind(
    WorkspaceFileKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_text_file(
    WorkspaceTextFile self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
