// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent_hooks.dart';
import 'api/git.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 590809161;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'alera_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiGitBranchExists({
    required String repoPath,
    required String branch,
  });

  Future<void> crateApiGitCloneRepository({
    required String url,
    required String destinationPath,
  });

  Future<void> crateApiGitCreateWorktree({
    required String repoPath,
    required String newBranch,
    required String path,
    required String sourceBranch,
  });

  Future<String> crateApiGitCurrentBranch({required String path});

  Future<void> crateApiGitDeleteBranch({
    required String repoPath,
    required String branch,
    required bool force,
  });

  Future<void> crateApiInitApp();

  Future<bool> crateApiGitIsGitRepository({required String path});

  Future<bool> crateApiGitIsValidBranchName({required String name});

  Future<List<String>> crateApiGitListBranches({required String path});

  Future<List<GitWorktreeEntry>> crateApiGitListWorktrees({
    required String repoPath,
  });

  Future<void> crateApiGitRemoveWorktree({
    required String repoPath,
    required String path,
    required bool force,
  });

  Future<void> crateApiAgentHooksSetAgentHookEnabledAgents({
    required List<String> enabledAgents,
  });

  Future<AgentHookEndpointDto> crateApiAgentHooksStartAgentHookReceiver({
    required String token,
    required List<String> enabledAgents,
  });

  Future<void> crateApiAgentHooksStopAgentHookReceiver();

  Stream<AgentHookEventBatchDto> crateApiAgentHooksWatchAgentHookEventBatches();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiGitBranchExists({
    required String repoPath,
    required String branch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(repoPath, serializer);
          sse_encode_String(branch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitBranchExistsConstMeta,
        argValues: [repoPath, branch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitBranchExistsConstMeta => const TaskConstMeta(
    debugName: "branch_exists",
    argNames: ["repoPath", "branch"],
  );

  @override
  Future<void> crateApiGitCloneRepository({
    required String url,
    required String destinationPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(destinationPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitCloneRepositoryConstMeta,
        argValues: [url, destinationPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitCloneRepositoryConstMeta => const TaskConstMeta(
    debugName: "clone_repository",
    argNames: ["url", "destinationPath"],
  );

  @override
  Future<void> crateApiGitCreateWorktree({
    required String repoPath,
    required String newBranch,
    required String path,
    required String sourceBranch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(repoPath, serializer);
          sse_encode_String(newBranch, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(sourceBranch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitCreateWorktreeConstMeta,
        argValues: [repoPath, newBranch, path, sourceBranch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitCreateWorktreeConstMeta => const TaskConstMeta(
    debugName: "create_worktree",
    argNames: ["repoPath", "newBranch", "path", "sourceBranch"],
  );

  @override
  Future<String> crateApiGitCurrentBranch({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitCurrentBranchConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitCurrentBranchConstMeta =>
      const TaskConstMeta(debugName: "current_branch", argNames: ["path"]);

  @override
  Future<void> crateApiGitDeleteBranch({
    required String repoPath,
    required String branch,
    required bool force,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(repoPath, serializer);
          sse_encode_String(branch, serializer);
          sse_encode_bool(force, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitDeleteBranchConstMeta,
        argValues: [repoPath, branch, force],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitDeleteBranchConstMeta => const TaskConstMeta(
    debugName: "delete_branch",
    argNames: ["repoPath", "branch", "force"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiGitIsGitRepository({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitIsGitRepositoryConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitIsGitRepositoryConstMeta =>
      const TaskConstMeta(debugName: "is_git_repository", argNames: ["path"]);

  @override
  Future<bool> crateApiGitIsValidBranchName({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitIsValidBranchNameConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitIsValidBranchNameConstMeta =>
      const TaskConstMeta(
        debugName: "is_valid_branch_name",
        argNames: ["name"],
      );

  @override
  Future<List<String>> crateApiGitListBranches({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitListBranchesConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitListBranchesConstMeta =>
      const TaskConstMeta(debugName: "list_branches", argNames: ["path"]);

  @override
  Future<List<GitWorktreeEntry>> crateApiGitListWorktrees({
    required String repoPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(repoPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_git_worktree_entry,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitListWorktreesConstMeta,
        argValues: [repoPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitListWorktreesConstMeta =>
      const TaskConstMeta(debugName: "list_worktrees", argNames: ["repoPath"]);

  @override
  Future<void> crateApiGitRemoveWorktree({
    required String repoPath,
    required String path,
    required bool force,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(repoPath, serializer);
          sse_encode_String(path, serializer);
          sse_encode_bool(force, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitRemoveWorktreeConstMeta,
        argValues: [repoPath, path, force],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitRemoveWorktreeConstMeta => const TaskConstMeta(
    debugName: "remove_worktree",
    argNames: ["repoPath", "path", "force"],
  );

  @override
  Future<void> crateApiAgentHooksSetAgentHookEnabledAgents({
    required List<String> enabledAgents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(enabledAgents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentHooksSetAgentHookEnabledAgentsConstMeta,
        argValues: [enabledAgents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentHooksSetAgentHookEnabledAgentsConstMeta =>
      const TaskConstMeta(
        debugName: "set_agent_hook_enabled_agents",
        argNames: ["enabledAgents"],
      );

  @override
  Future<AgentHookEndpointDto> crateApiAgentHooksStartAgentHookReceiver({
    required String token,
    required List<String> enabledAgents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_list_String(enabledAgents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_hook_endpoint_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentHooksStartAgentHookReceiverConstMeta,
        argValues: [token, enabledAgents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentHooksStartAgentHookReceiverConstMeta =>
      const TaskConstMeta(
        debugName: "start_agent_hook_receiver",
        argNames: ["token", "enabledAgents"],
      );

  @override
  Future<void> crateApiAgentHooksStopAgentHookReceiver() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentHooksStopAgentHookReceiverConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentHooksStopAgentHookReceiverConstMeta =>
      const TaskConstMeta(debugName: "stop_agent_hook_receiver", argNames: []);

  @override
  Stream<AgentHookEventBatchDto>
  crateApiAgentHooksWatchAgentHookEventBatches() {
    final sink = RustStreamSink<AgentHookEventBatchDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_agent_hook_event_batch_dto_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiAgentHooksWatchAgentHookEventBatchesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAgentHooksWatchAgentHookEventBatchesConstMeta =>
      const TaskConstMeta(
        debugName: "watch_agent_hook_event_batches",
        argNames: ["sink"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<AgentHookEventBatchDto>
  dco_decode_StreamSink_agent_hook_event_batch_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentHookEndpointDto dco_decode_agent_hook_endpoint_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return AgentHookEndpointDto(port: dco_decode_u_16(arr[0]));
  }

  @protected
  AgentHookEventBatchDto dco_decode_agent_hook_event_batch_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AgentHookEventBatchDto(
      events: dco_decode_list_agent_hook_event_dto(arr[0]),
      coalescedIntermediateCount: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  AgentHookEventDto dco_decode_agent_hook_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return AgentHookEventDto(
      terminalSessionId: dco_decode_String(arr[0]),
      workspaceId: dco_decode_String(arr[1]),
      tabId: dco_decode_String(arr[2]),
      agentType: dco_decode_String(arr[3]),
      payloadJson: dco_decode_String(arr[4]),
      hookEventName: dco_decode_opt_String(arr[5]),
      version: dco_decode_opt_String(arr[6]),
      inferredEventName: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  GitError dco_decode_git_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GitError(
      kind: dco_decode_git_error_kind(arr[0]),
      context: dco_decode_String(arr[1]),
    );
  }

  @protected
  GitErrorKind dco_decode_git_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GitErrorKind.values[raw as int];
  }

  @protected
  GitWorktreeEntry dco_decode_git_worktree_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GitWorktreeEntry(
      path: dco_decode_String(arr[0]),
      branch: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AgentHookEventDto> dco_decode_list_agent_hook_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_agent_hook_event_dto).toList();
  }

  @protected
  List<GitWorktreeEntry> dco_decode_list_git_worktree_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_git_worktree_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<AgentHookEventBatchDto>
  sse_decode_StreamSink_agent_hook_event_batch_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentHookEndpointDto sse_decode_agent_hook_endpoint_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_port = sse_decode_u_16(deserializer);
    return AgentHookEndpointDto(port: var_port);
  }

  @protected
  AgentHookEventBatchDto sse_decode_agent_hook_event_batch_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_events = sse_decode_list_agent_hook_event_dto(deserializer);
    var var_coalescedIntermediateCount = sse_decode_u_32(deserializer);
    return AgentHookEventBatchDto(
      events: var_events,
      coalescedIntermediateCount: var_coalescedIntermediateCount,
    );
  }

  @protected
  AgentHookEventDto sse_decode_agent_hook_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_terminalSessionId = sse_decode_String(deserializer);
    var var_workspaceId = sse_decode_String(deserializer);
    var var_tabId = sse_decode_String(deserializer);
    var var_agentType = sse_decode_String(deserializer);
    var var_payloadJson = sse_decode_String(deserializer);
    var var_hookEventName = sse_decode_opt_String(deserializer);
    var var_version = sse_decode_opt_String(deserializer);
    var var_inferredEventName = sse_decode_opt_String(deserializer);
    return AgentHookEventDto(
      terminalSessionId: var_terminalSessionId,
      workspaceId: var_workspaceId,
      tabId: var_tabId,
      agentType: var_agentType,
      payloadJson: var_payloadJson,
      hookEventName: var_hookEventName,
      version: var_version,
      inferredEventName: var_inferredEventName,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  GitError sse_decode_git_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_git_error_kind(deserializer);
    var var_context = sse_decode_String(deserializer);
    return GitError(kind: var_kind, context: var_context);
  }

  @protected
  GitErrorKind sse_decode_git_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GitErrorKind.values[inner];
  }

  @protected
  GitWorktreeEntry sse_decode_git_worktree_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_branch = sse_decode_String(deserializer);
    return GitWorktreeEntry(path: var_path, branch: var_branch);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AgentHookEventDto> sse_decode_list_agent_hook_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AgentHookEventDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_agent_hook_event_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<GitWorktreeEntry> sse_decode_list_git_worktree_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GitWorktreeEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_git_worktree_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_agent_hook_event_batch_dto_Sse(
    RustStreamSink<AgentHookEventBatchDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_hook_event_batch_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_hook_endpoint_dto(
    AgentHookEndpointDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_agent_hook_event_batch_dto(
    AgentHookEventBatchDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_agent_hook_event_dto(self.events, serializer);
    sse_encode_u_32(self.coalescedIntermediateCount, serializer);
  }

  @protected
  void sse_encode_agent_hook_event_dto(
    AgentHookEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.terminalSessionId, serializer);
    sse_encode_String(self.workspaceId, serializer);
    sse_encode_String(self.tabId, serializer);
    sse_encode_String(self.agentType, serializer);
    sse_encode_String(self.payloadJson, serializer);
    sse_encode_opt_String(self.hookEventName, serializer);
    sse_encode_opt_String(self.version, serializer);
    sse_encode_opt_String(self.inferredEventName, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_git_error(GitError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_git_error_kind(self.kind, serializer);
    sse_encode_String(self.context, serializer);
  }

  @protected
  void sse_encode_git_error_kind(GitErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_git_worktree_entry(
    GitWorktreeEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.branch, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_agent_hook_event_dto(
    List<AgentHookEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_agent_hook_event_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_git_worktree_entry(
    List<GitWorktreeEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_git_worktree_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
