// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/agent_hooks.dart';
import 'api/git.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AgentHookEventBatchDto>
  dco_decode_StreamSink_agent_hook_event_batch_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentHookEndpointDto dco_decode_agent_hook_endpoint_dto(dynamic raw);

  @protected
  AgentHookEventBatchDto dco_decode_agent_hook_event_batch_dto(dynamic raw);

  @protected
  AgentHookEventDto dco_decode_agent_hook_event_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  GitError dco_decode_git_error(dynamic raw);

  @protected
  GitErrorKind dco_decode_git_error_kind(dynamic raw);

  @protected
  GitWorktreeEntry dco_decode_git_worktree_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AgentHookEventDto> dco_decode_list_agent_hook_event_dto(dynamic raw);

  @protected
  List<GitWorktreeEntry> dco_decode_list_git_worktree_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AgentHookEventBatchDto>
  sse_decode_StreamSink_agent_hook_event_batch_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentHookEndpointDto sse_decode_agent_hook_endpoint_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentHookEventBatchDto sse_decode_agent_hook_event_batch_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentHookEventDto sse_decode_agent_hook_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  GitError sse_decode_git_error(SseDeserializer deserializer);

  @protected
  GitErrorKind sse_decode_git_error_kind(SseDeserializer deserializer);

  @protected
  GitWorktreeEntry sse_decode_git_worktree_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AgentHookEventDto> sse_decode_list_agent_hook_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GitWorktreeEntry> sse_decode_list_git_worktree_entry(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_agent_hook_event_batch_dto_Sse(
    RustStreamSink<AgentHookEventBatchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_hook_endpoint_dto(
    AgentHookEndpointDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_hook_event_batch_dto(
    AgentHookEventBatchDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_hook_event_dto(
    AgentHookEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_git_error(GitError self, SseSerializer serializer);

  @protected
  void sse_encode_git_error_kind(GitErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_git_worktree_entry(
    GitWorktreeEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agent_hook_event_dto(
    List<AgentHookEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_worktree_entry(
    List<GitWorktreeEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
