// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../git.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<GitHostedReviewRange> gitFetchHostedReviewRange({
  required String path,
  required String baseBranch,
  required String headSha,
  String? reviewRef,
}) => RustLib.instance.api.crateApiGitGitHostedReviewGitFetchHostedReviewRange(
  path: path,
  baseBranch: baseBranch,
  headSha: headSha,
  reviewRef: reviewRef,
);

class GitHostedReviewRange {
  final String baseOid;
  final String headOid;

  const GitHostedReviewRange({required this.baseOid, required this.headOid});

  @override
  int get hashCode => baseOid.hashCode ^ headOid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitHostedReviewRange &&
          runtimeType == other.runtimeType &&
          baseOid == other.baseOid &&
          headOid == other.headOid;
}
