// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../git.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<GitHostedReviewRange> gitFetchHostedReviewRange({
  required String path,
  required String remoteName,
  required String baseBranch,
  required String headSha,
  String? headRemote,
  String? comparisonBaseSha,
  String? mergeCommitSha,
  String? reviewRef,
}) => RustLib.instance.api.crateApiGitGitHostedReviewGitFetchHostedReviewRange(
  path: path,
  remoteName: remoteName,
  baseBranch: baseBranch,
  headSha: headSha,
  headRemote: headRemote,
  comparisonBaseSha: comparisonBaseSha,
  mergeCommitSha: mergeCommitSha,
  reviewRef: reviewRef,
);

Future<void> gitReleaseHostedReviewRange({
  required String path,
  required String retentionId,
}) =>
    RustLib.instance.api.crateApiGitGitHostedReviewGitReleaseHostedReviewRange(
      path: path,
      retentionId: retentionId,
    );

Future<void> gitPersistHostedReviewRange({
  required String path,
  required String retentionId,
}) =>
    RustLib.instance.api.crateApiGitGitHostedReviewGitPersistHostedReviewRange(
      path: path,
      retentionId: retentionId,
    );

class GitHostedReviewRange {
  final String baseOid;
  final String headOid;
  final String retentionId;

  const GitHostedReviewRange({
    required this.baseOid,
    required this.headOid,
    required this.retentionId,
  });

  @override
  int get hashCode =>
      baseOid.hashCode ^ headOid.hashCode ^ retentionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitHostedReviewRange &&
          runtimeType == other.runtimeType &&
          baseOid == other.baseOid &&
          headOid == other.headOid &&
          retentionId == other.retentionId;
}
