Map<String, Object?> workflowControlsFixture({
  int sequence = 0,
  String executionStatus = 'paused',
  bool gateReady = true,
}) => {
  'runId': 'run',
  'revision': 1,
  'status': 'approved',
  'canControl': true,
  'canCancel': true,
  'canCorrect': false,
  'cancellationPending': 0,
  'cancellationError': null,
  'sourceSha': 'a' * 40,
  'integrationSha': 'b' * 40,
  'recipeName': 'Feature Delivery',
  'recipeSource': {'origin': 'builtIn', 'id': 'feature-delivery'},
  'execution': {
    'runId': 'run',
    'revision': 1,
    'sequence': sequence,
    'status': executionStatus,
  },
  'stages': [
    {
      'id': 'foundation',
      'name': 'Foundation',
      'dependsOn': <String>[],
      'gate': 'foundation',
      'gateStatus': 'pending',
      'canReview': gateReady,
      'taskCount': 1,
      'integratedCount': 1,
    },
    {
      'id': 'implementation',
      'name': 'Implementation',
      'dependsOn': ['foundation'],
      'gate': null,
      'gateStatus': null,
      'canReview': false,
      'taskCount': 2,
      'integratedCount': 0,
    },
    {
      'id': 'product',
      'name': 'Product Validation',
      'dependsOn': ['implementation'],
      'gate': 'product',
      'gateStatus': 'pending',
      'canReview': false,
      'taskCount': 1,
      'integratedCount': 0,
    },
  ],
};
