analyzer:
  exclude:
    - build/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_primary_constructor_body: true
    unnecessary_const_in_enum_constructor: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    directives_ordering: true
    prefer_final_locals: true
    unawaited_futures: true
