// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Saves an image-only clipboard payload as a private temporary PNG.
///
/// Returns `Ok(None)` when the clipboard has no image representation. The
/// bridge runs this synchronous function off the Flutter UI isolate.
Future<String?> saveClipboardImageAsTempFile() =>
    RustLib.instance.api.crateApiClipboardSaveClipboardImageAsTempFile();
