// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `canonical`, `existing_worktree_admin_names`, `from_git2`, `has_configured_remote_for_tracking_branch`, `head_branch_name`, `is_path_occupied`, `new`, `open_repo`, `remote_tracking_upstream_name`, `split_clone_destination`, `unborn_branch_name`, `unique_worktree_admin_name`, `worktree_admin_name`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`

/// Returns `true` when `path` resolves to a git repository (work tree). Mirrors
/// `git rev-parse --is-inside-work-tree`; surfaces permission failures as
/// [`GitErrorKind::AccessDenied`] so the UI can explain sandbox denials.
Future<bool> isGitRepository({required String path}) =>
    RustLib.instance.api.crateApiGitIsGitRepository(path: path);

/// Lists local and remote-tracking branch short names, sorted and de-duplicated,
/// excluding `*/HEAD` symbolic entries. Mirrors
/// `git for-each-ref --format=%(refname:short) refs/heads refs/remotes`.
Future<List<String>> listBranches({required String path}) =>
    RustLib.instance.api.crateApiGitListBranches(path: path);

/// Returns the current branch short name, or `HEAD` when detached. Mirrors
/// `git branch --show-current`.
Future<String> currentBranch({required String path}) =>
    RustLib.instance.api.crateApiGitCurrentBranch(path: path);

/// Returns `true` when a local branch named `branch` exists.
Future<bool> branchExists({required String repoPath, required String branch}) =>
    RustLib.instance.api.crateApiGitBranchExists(
      repoPath: repoPath,
      branch: branch,
    );

/// Validates a branch name. Mirrors `git check-ref-format --branch`.
Future<bool> isValidBranchName({required String name}) =>
    RustLib.instance.api.crateApiGitIsValidBranchName(name: name);

/// Creates `new_branch` from `source_branch` and adds a linked worktree at
/// `path`. Mirrors `git worktree add -b <new_branch> <path> <source_branch>`.
Future<void> createWorktree({
  required String repoPath,
  required String newBranch,
  required String path,
  required String sourceBranch,
}) => RustLib.instance.api.crateApiGitCreateWorktree(
  repoPath: repoPath,
  newBranch: newBranch,
  path: path,
  sourceBranch: sourceBranch,
);

/// Removes the worktree whose checkout lives at `path`, deleting the working
/// tree files. Mirrors `git worktree remove --force <path>`.
Future<void> removeWorktree({
  required String repoPath,
  required String path,
  required bool force,
}) => RustLib.instance.api.crateApiGitRemoveWorktree(
  repoPath: repoPath,
  path: path,
  force: force,
);

/// Force-deletes a local branch. Mirrors `git branch -D <branch>`.
Future<void> deleteBranch({
  required String repoPath,
  required String branch,
  required bool force,
}) => RustLib.instance.api.crateApiGitDeleteBranch(
  repoPath: repoPath,
  branch: branch,
  force: force,
);

/// Lists the main work tree plus every linked worktree, with each entry's
/// branch short name. Mirrors `git worktree list --porcelain` (the main work
/// tree is included so callers can use its presence as a liveness guard).
Future<List<GitWorktreeEntry>> listWorktrees({required String repoPath}) =>
    RustLib.instance.api.crateApiGitListWorktrees(repoPath: repoPath);

/// Clones a repository into `destination_path` using the system `git` CLI so
/// the user's credential helper authenticates private remotes. Mirrors
/// `git clone --progress -- <url> <destination_path>`.
Future<void> cloneRepository({
  required String url,
  required String destinationPath,
}) => RustLib.instance.api.crateApiGitCloneRepository(
  url: url,
  destinationPath: destinationPath,
);

/// Structured git failure surfaced to Dart. `context` carries the relevant
/// detail for the [`GitErrorKind`] (an offending path, branch name, or the
/// underlying git message). The Dart `RustGitBackend` translates each kind into
/// a domain `GitException`.
class GitError implements FrbException {
  final GitErrorKind kind;
  final String context;

  const GitError({required this.kind, required this.context});

  @override
  int get hashCode => kind.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          context == other.context;
}

/// Discriminates the structured git failures surfaced to Dart. Kept as a plain
/// (field-less) enum so flutter_rust_bridge mirrors it as a Dart `enum` without
/// pulling in `freezed`.
enum GitErrorKind {
  notARepository,
  accessDenied,
  branchNotFound,
  branchAlreadyExists,
  invalidBranchName,
  worktreeAlreadyExists,
  worktreeNotFound,
  cloneFailed,
  gitCli,
  internal,
}

/// A single git worktree entry, mirroring one record of `git worktree list`.
class GitWorktreeEntry {
  final String path;
  final String branch;

  const GitWorktreeEntry({required this.path, required this.branch});

  @override
  int get hashCode => path.hashCode ^ branch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitWorktreeEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          branch == other.branch;
}
