// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `canonical`, `commit_parent_commits`, `current_head_commit`, `delete_workspace_relative_path`, `discard_status_entries`, `entries_for_area_and_scope`, `existing_worktree_admin_names`, `from_git2`, `from_io`, `git_cli_in_path`, `git_signature`, `has_configured_remote_for_tracking_branch`, `head_branch_name`, `is_path_occupied`, `merge_head_oids`, `new`, `open_repo`, `pathspec_string`, `reject_out_of_scope_staged_entries`, `reject_out_of_scope_stash_pop`, `reject_out_of_scope_tracked_changes`, `reject_tree_diff_out_of_scope`, `relative_path`, `remote_tracking_upstream_name`, `remove_index_path_if_present`, `repo_path_is_in_scope`, `repo_relative_path_from_workspace`, `repo_relative_path`, `repo_workdir_path_exists`, `repository_has_conflicts`, `scoped_pathspecs`, `split_clone_destination`, `stage_selected_path`, `stage_status_entries`, `stash_oid`, `unborn_branch_name`, `unique_worktree_admin_name`, `unstage_selected_path`, `unstage_status_entries`, `workspace_path_is_in_scope`, `workspace_repo_relative_path`, `worktree_admin_name`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<bool> isGitRepository({required String path}) =>
    RustLib.instance.api.crateApiGitIsGitRepository(path: path);

Future<List<String>> listBranches({required String path}) =>
    RustLib.instance.api.crateApiGitListBranches(path: path);

Future<String> currentBranch({required String path}) =>
    RustLib.instance.api.crateApiGitCurrentBranch(path: path);

Future<bool> branchExists({required String repoPath, required String branch}) =>
    RustLib.instance.api.crateApiGitBranchExists(
      repoPath: repoPath,
      branch: branch,
    );

Future<bool> isValidBranchName({required String name}) =>
    RustLib.instance.api.crateApiGitIsValidBranchName(name: name);

Future<GitStatusResult> gitStatus({required String path}) =>
    RustLib.instance.api.crateApiGitGitStatus(path: path);

Future<GitStatusResult> gitStatusForPath({
  required String path,
  required String filePath,
}) => RustLib.instance.api.crateApiGitGitStatusForPath(
  path: path,
  filePath: filePath,
);

Future<GitDiffResult> gitDiff({
  required String path,
  required String filePath,
  required GitChangeArea area,
}) => RustLib.instance.api.crateApiGitGitDiff(
  path: path,
  filePath: filePath,
  area: area,
);

Future<GitDiffResult> gitDiffAll({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitDiffAll(path: path, filePath: filePath);

Future<GitRepositoryState> gitRepositoryState({required String path}) =>
    RustLib.instance.api.crateApiGitGitRepositoryState(path: path);

Future<void> gitStage({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitStage(path: path, filePath: filePath);

Future<void> gitStageArea({
  required String path,
  required GitChangeArea area,
  String? filePath,
}) => RustLib.instance.api.crateApiGitGitStageArea(
  path: path,
  area: area,
  filePath: filePath,
);

Future<void> gitUnstage({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitUnstage(path: path, filePath: filePath);

Future<void> gitUnstageArea({
  required String path,
  required GitChangeArea area,
  String? filePath,
}) => RustLib.instance.api.crateApiGitGitUnstageArea(
  path: path,
  area: area,
  filePath: filePath,
);

Future<void> gitDiscard({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitDiscard(path: path, filePath: filePath);

Future<void> gitDiscardArea({
  required String path,
  required GitChangeArea area,
  String? filePath,
}) => RustLib.instance.api.crateApiGitGitDiscardArea(
  path: path,
  area: area,
  filePath: filePath,
);

Future<String> gitCommit({required String path, required String message}) =>
    RustLib.instance.api.crateApiGitGitCommit(path: path, message: message);

Future<void> gitFetch({required String path}) =>
    RustLib.instance.api.crateApiGitGitFetch(path: path);

Future<void> gitPull({required String path}) =>
    RustLib.instance.api.crateApiGitGitPull(path: path);

Future<void> gitPush({required String path}) =>
    RustLib.instance.api.crateApiGitGitPush(path: path);

Future<List<GitStashEntry>> gitListStashes({required String path}) =>
    RustLib.instance.api.crateApiGitGitListStashes(path: path);

Future<void> gitStash({required String path}) =>
    RustLib.instance.api.crateApiGitGitStash(path: path);

Future<void> gitStashPop({required String path, required int stashIndex}) =>
    RustLib.instance.api.crateApiGitGitStashPop(
      path: path,
      stashIndex: stashIndex,
    );

/// Creates `new_branch` from `source_branch` and adds a linked worktree at
/// `path`. Mirrors `git worktree add -b <new_branch> <path> <source_branch>`.
Future<void> createWorktree({
  required String repoPath,
  required String newBranch,
  required String path,
  required String sourceBranch,
}) => RustLib.instance.api.crateApiGitCreateWorktree(
  repoPath: repoPath,
  newBranch: newBranch,
  path: path,
  sourceBranch: sourceBranch,
);

/// Removes the worktree whose checkout lives at `path`, deleting the working
/// tree files. Mirrors `git worktree remove --force <path>`.
Future<void> removeWorktree({
  required String repoPath,
  required String path,
  required bool force,
}) => RustLib.instance.api.crateApiGitRemoveWorktree(
  repoPath: repoPath,
  path: path,
  force: force,
);

/// Force-deletes a local branch. Mirrors `git branch -D <branch>`.
Future<void> deleteBranch({
  required String repoPath,
  required String branch,
  required bool force,
}) => RustLib.instance.api.crateApiGitDeleteBranch(
  repoPath: repoPath,
  branch: branch,
  force: force,
);

/// Lists the main work tree plus every linked worktree, with each entry's
/// branch short name. Mirrors `git worktree list --porcelain` (the main work
/// tree is included so callers can use its presence as a liveness guard).
Future<List<GitWorktreeEntry>> listWorktrees({required String repoPath}) =>
    RustLib.instance.api.crateApiGitListWorktrees(repoPath: repoPath);

/// Clones a repository into `destination_path` using the system `git` CLI so
/// the user's credential helper authenticates private remotes. Mirrors
/// `git clone --progress -- <url> <destination_path>`.
Future<void> cloneRepository({
  required String url,
  required String destinationPath,
}) => RustLib.instance.api.crateApiGitCloneRepository(
  url: url,
  destinationPath: destinationPath,
);

enum GitChangeArea { untracked, unstaged, staged }

class GitChangeEntry {
  final String path;
  final String? oldPath;
  final GitChangeArea area;
  final GitChangeStatus status;
  final int? added;
  final int? removed;
  final bool isBinary;
  final bool isLarge;

  const GitChangeEntry({
    required this.path,
    this.oldPath,
    required this.area,
    required this.status,
    this.added,
    this.removed,
    required this.isBinary,
    required this.isLarge,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      oldPath.hashCode ^
      area.hashCode ^
      status.hashCode ^
      added.hashCode ^
      removed.hashCode ^
      isBinary.hashCode ^
      isLarge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitChangeEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oldPath == other.oldPath &&
          area == other.area &&
          status == other.status &&
          added == other.added &&
          removed == other.removed &&
          isBinary == other.isBinary &&
          isLarge == other.isLarge;
}

class GitChangeGroup {
  final GitChangeArea area;
  final List<GitChangeEntry> entries;
  final List<GitChangeTreeRow> treeRows;

  const GitChangeGroup({
    required this.area,
    required this.entries,
    required this.treeRows,
  });

  @override
  int get hashCode => area.hashCode ^ entries.hashCode ^ treeRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitChangeGroup &&
          runtimeType == other.runtimeType &&
          area == other.area &&
          entries == other.entries &&
          treeRows == other.treeRows;
}

enum GitChangeStatus { modified, added, deleted, renamed, copied, untracked }

class GitChangeTreeRow {
  final GitChangeTreeRowKind kind;
  final String name;
  final String path;
  final int depth;
  final int fileCount;
  final GitChangeEntry? entry;

  const GitChangeTreeRow({
    required this.kind,
    required this.name,
    required this.path,
    required this.depth,
    required this.fileCount,
    this.entry,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      name.hashCode ^
      path.hashCode ^
      depth.hashCode ^
      fileCount.hashCode ^
      entry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitChangeTreeRow &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          name == other.name &&
          path == other.path &&
          depth == other.depth &&
          fileCount == other.fileCount &&
          entry == other.entry;
}

enum GitChangeTreeRowKind { directory, file }

class GitDiffFile {
  final String path;
  final String? oldPath;
  final GitChangeArea area;
  final GitChangeStatus status;
  final List<GitDiffLine> lines;
  final int? added;
  final int? removed;
  final bool isBinary;
  final bool isLarge;
  final bool truncated;
  final bool linePreviewTruncated;

  const GitDiffFile({
    required this.path,
    this.oldPath,
    required this.area,
    required this.status,
    required this.lines,
    this.added,
    this.removed,
    required this.isBinary,
    required this.isLarge,
    required this.truncated,
    required this.linePreviewTruncated,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      oldPath.hashCode ^
      area.hashCode ^
      status.hashCode ^
      lines.hashCode ^
      added.hashCode ^
      removed.hashCode ^
      isBinary.hashCode ^
      isLarge.hashCode ^
      truncated.hashCode ^
      linePreviewTruncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oldPath == other.oldPath &&
          area == other.area &&
          status == other.status &&
          lines == other.lines &&
          added == other.added &&
          removed == other.removed &&
          isBinary == other.isBinary &&
          isLarge == other.isLarge &&
          truncated == other.truncated &&
          linePreviewTruncated == other.linePreviewTruncated;
}

class GitDiffLine {
  final String text;
  final GitDiffLineKind kind;

  const GitDiffLine({required this.text, required this.kind});

  @override
  int get hashCode => text.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffLine &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          kind == other.kind;
}

enum GitDiffLineKind { addition, deletion, hunk, header, context }

class GitDiffResult {
  final List<GitDiffFile> files;
  final bool truncated;

  const GitDiffResult({required this.files, required this.truncated});

  @override
  int get hashCode => files.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffResult &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          truncated == other.truncated;
}

class GitError implements FrbException {
  final GitErrorKind kind;
  final String context;

  const GitError({required this.kind, required this.context});

  @override
  int get hashCode => kind.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          context == other.context;
}

enum GitErrorKind {
  notARepository,
  accessDenied,
  branchNotFound,
  branchAlreadyExists,
  invalidBranchName,
  worktreeAlreadyExists,
  worktreeNotFound,
  cloneFailed,
  gitCli,
  detachedHead,
  noUpstream,
  remoteNotFound,
  nothingToCommit,
  conflict,
  workspaceScope,
  missingIdentity,
  internal,
}

class GitRepositoryState {
  final String branch;
  final String? upstream;
  final int ahead;
  final int behind;
  final bool hasConflicts;

  const GitRepositoryState({
    required this.branch,
    this.upstream,
    required this.ahead,
    required this.behind,
    required this.hasConflicts,
  });

  @override
  int get hashCode =>
      branch.hashCode ^
      upstream.hashCode ^
      ahead.hashCode ^
      behind.hashCode ^
      hasConflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRepositoryState &&
          runtimeType == other.runtimeType &&
          branch == other.branch &&
          upstream == other.upstream &&
          ahead == other.ahead &&
          behind == other.behind &&
          hasConflicts == other.hasConflicts;
}

class GitStashEntry {
  final int index;
  final String reference;
  final String message;
  final String oid;

  const GitStashEntry({
    required this.index,
    required this.reference,
    required this.message,
    required this.oid,
  });

  @override
  int get hashCode =>
      index.hashCode ^ reference.hashCode ^ message.hashCode ^ oid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitStashEntry &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          reference == other.reference &&
          message == other.message &&
          oid == other.oid;
}

class GitStatusResult {
  final List<GitChangeEntry> entries;
  final List<GitChangeGroup> groups;

  const GitStatusResult({required this.entries, required this.groups});

  @override
  int get hashCode => entries.hashCode ^ groups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitStatusResult &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          groups == other.groups;
}

class GitWorktreeEntry {
  final String path;
  final String branch;

  const GitWorktreeEntry({required this.path, required this.branch});

  @override
  int get hashCode => path.hashCode ^ branch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitWorktreeEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          branch == other.branch;
}
