// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `canonical`, `existing_worktree_admin_names`, `from_git2`, `has_configured_remote_for_tracking_branch`, `head_branch_name`, `is_path_occupied`, `new`, `open_repo`, `remote_tracking_upstream_name`, `split_clone_destination`, `unborn_branch_name`, `unique_worktree_admin_name`, `worktree_admin_name`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

Future<bool> isGitRepository({required String path}) =>
    RustLib.instance.api.crateApiGitIsGitRepository(path: path);

Future<List<String>> listBranches({required String path}) =>
    RustLib.instance.api.crateApiGitListBranches(path: path);

Future<String> currentBranch({required String path}) =>
    RustLib.instance.api.crateApiGitCurrentBranch(path: path);

Future<bool> branchExists({required String repoPath, required String branch}) =>
    RustLib.instance.api.crateApiGitBranchExists(
      repoPath: repoPath,
      branch: branch,
    );

Future<bool> isValidBranchName({required String name}) =>
    RustLib.instance.api.crateApiGitIsValidBranchName(name: name);

Future<GitStatusResult> gitStatus({required String path}) =>
    RustLib.instance.api.crateApiGitGitStatus(path: path);

Future<GitDiffResult> gitDiff({
  required String path,
  required String filePath,
  required GitChangeArea area,
}) => RustLib.instance.api.crateApiGitGitDiff(
  path: path,
  filePath: filePath,
  area: area,
);

Future<GitDiffResult> gitDiffAll({required String path, String? filePath}) =>
    RustLib.instance.api.crateApiGitGitDiffAll(path: path, filePath: filePath);

/// Creates `new_branch` from `source_branch` and adds a linked worktree at
/// `path`. Mirrors `git worktree add -b <new_branch> <path> <source_branch>`.
Future<void> createWorktree({
  required String repoPath,
  required String newBranch,
  required String path,
  required String sourceBranch,
}) => RustLib.instance.api.crateApiGitCreateWorktree(
  repoPath: repoPath,
  newBranch: newBranch,
  path: path,
  sourceBranch: sourceBranch,
);

/// Removes the worktree whose checkout lives at `path`, deleting the working
/// tree files. Mirrors `git worktree remove --force <path>`.
Future<void> removeWorktree({
  required String repoPath,
  required String path,
  required bool force,
}) => RustLib.instance.api.crateApiGitRemoveWorktree(
  repoPath: repoPath,
  path: path,
  force: force,
);

/// Force-deletes a local branch. Mirrors `git branch -D <branch>`.
Future<void> deleteBranch({
  required String repoPath,
  required String branch,
  required bool force,
}) => RustLib.instance.api.crateApiGitDeleteBranch(
  repoPath: repoPath,
  branch: branch,
  force: force,
);

/// Lists the main work tree plus every linked worktree, with each entry's
/// branch short name. Mirrors `git worktree list --porcelain` (the main work
/// tree is included so callers can use its presence as a liveness guard).
Future<List<GitWorktreeEntry>> listWorktrees({required String repoPath}) =>
    RustLib.instance.api.crateApiGitListWorktrees(repoPath: repoPath);

/// Clones a repository into `destination_path` using the system `git` CLI so
/// the user's credential helper authenticates private remotes. Mirrors
/// `git clone --progress -- <url> <destination_path>`.
Future<void> cloneRepository({
  required String url,
  required String destinationPath,
}) => RustLib.instance.api.crateApiGitCloneRepository(
  url: url,
  destinationPath: destinationPath,
);

enum GitChangeArea { untracked, unstaged, staged }

class GitChangeEntry {
  final String path;
  final String? oldPath;
  final GitChangeArea area;
  final GitChangeStatus status;
  final int? added;
  final int? removed;
  final bool isBinary;
  final bool isLarge;

  const GitChangeEntry({
    required this.path,
    this.oldPath,
    required this.area,
    required this.status,
    this.added,
    this.removed,
    required this.isBinary,
    required this.isLarge,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      oldPath.hashCode ^
      area.hashCode ^
      status.hashCode ^
      added.hashCode ^
      removed.hashCode ^
      isBinary.hashCode ^
      isLarge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitChangeEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oldPath == other.oldPath &&
          area == other.area &&
          status == other.status &&
          added == other.added &&
          removed == other.removed &&
          isBinary == other.isBinary &&
          isLarge == other.isLarge;
}

enum GitChangeStatus { modified, added, deleted, renamed, copied, untracked }

class GitDiffFile {
  final String path;
  final String? oldPath;
  final GitChangeArea area;
  final GitChangeStatus status;
  final String patch;
  final int? added;
  final int? removed;
  final bool isBinary;
  final bool isLarge;
  final bool truncated;

  const GitDiffFile({
    required this.path,
    this.oldPath,
    required this.area,
    required this.status,
    required this.patch,
    this.added,
    this.removed,
    required this.isBinary,
    required this.isLarge,
    required this.truncated,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      oldPath.hashCode ^
      area.hashCode ^
      status.hashCode ^
      patch.hashCode ^
      added.hashCode ^
      removed.hashCode ^
      isBinary.hashCode ^
      isLarge.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oldPath == other.oldPath &&
          area == other.area &&
          status == other.status &&
          patch == other.patch &&
          added == other.added &&
          removed == other.removed &&
          isBinary == other.isBinary &&
          isLarge == other.isLarge &&
          truncated == other.truncated;
}

class GitDiffResult {
  final List<GitDiffFile> files;
  final bool truncated;

  const GitDiffResult({required this.files, required this.truncated});

  @override
  int get hashCode => files.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitDiffResult &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          truncated == other.truncated;
}

class GitError implements FrbException {
  final GitErrorKind kind;
  final String context;

  const GitError({required this.kind, required this.context});

  @override
  int get hashCode => kind.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          context == other.context;
}

enum GitErrorKind {
  notARepository,
  accessDenied,
  branchNotFound,
  branchAlreadyExists,
  invalidBranchName,
  worktreeAlreadyExists,
  worktreeNotFound,
  cloneFailed,
  gitCli,
  internal,
}

class GitStatusResult {
  final List<GitChangeEntry> entries;

  const GitStatusResult({required this.entries});

  @override
  int get hashCode => entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitStatusResult &&
          runtimeType == other.runtimeType &&
          entries == other.entries;
}

class GitWorktreeEntry {
  final String path;
  final String branch;

  const GitWorktreeEntry({required this.path, required this.branch});

  @override
  int get hashCode => path.hashCode ^ branch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitWorktreeEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          branch == other.branch;
}
