// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'git.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `merge_explorer_status`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

Future<GitExplorerStatusSnapshot> gitExplorerStatusSnapshot({
  required String path,
}) => RustLib.instance.api.crateApiGitExplorerStatusGitExplorerStatusSnapshot(
  path: path,
);

enum GitExplorerStatus { untracked, added, modified }

class GitExplorerStatusEntry {
  final String path;
  final GitExplorerStatus status;

  const GitExplorerStatusEntry({required this.path, required this.status});

  @override
  int get hashCode => path.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitExplorerStatusEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          status == other.status;
}

class GitExplorerStatusSnapshot {
  final List<GitExplorerStatusEntry> entries;

  const GitExplorerStatusSnapshot({required this.entries});

  @override
  int get hashCode => entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitExplorerStatusSnapshot &&
          runtimeType == other.runtimeType &&
          entries == other.entries;
}
