// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_status`, `create_keep_awake`, `disable`, `enable`, `global_controller`, `has_owner`, `inactive_status`, `lock_owner`, `new`, `production`, `set_enabled`, `status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `KeepAliveController`, `KeepAliveOwner`

/// Enable or disable idle and display sleep prevention for this process.
Future<KeepAliveStatusDto> setKeepAlive({required bool enabled}) =>
    RustLib.instance.api.crateApiKeepAliveSetKeepAlive(enabled: enabled);

/// Current keep-alive lock state for this process.
Future<KeepAliveStatusDto> keepAliveStatus() =>
    RustLib.instance.api.crateApiKeepAliveKeepAliveStatus();

class KeepAliveStatusDto {
  final bool active;
  final bool system;
  final bool display;
  final String? error;

  const KeepAliveStatusDto({
    required this.active,
    required this.system,
    required this.display,
    this.error,
  });

  @override
  int get hashCode =>
      active.hashCode ^ system.hashCode ^ display.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeepAliveStatusDto &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          system == other.system &&
          display == other.display &&
          error == other.error;
}
