// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Runs a command to completion and returns everything it wrote.
Future<ProcessRunResult> processRun({
  required String executable,
  required List<String> arguments,
  String? workingDirectory,
  Map<String, String>? environment,
}) => RustLib.instance.api.crateApiProcessProcessRun(
  executable: executable,
  arguments: arguments,
  workingDirectory: workingDirectory,
  environment: environment,
);

/// Starts a command and streams its output until it exits. A spawn that fails
/// reports a `Failure` event rather than an error, so callers only ever read the
/// stream. The session id is valid until `Exit` or `Failure` arrives.
Stream<ProcessEvent> processStart({
  required String executable,
  required List<String> arguments,
  String? workingDirectory,
  Map<String, String>? environment,
  required bool includeParentEnvironment,
}) => RustLib.instance.api.crateApiProcessProcessStart(
  executable: executable,
  arguments: arguments,
  workingDirectory: workingDirectory,
  environment: environment,
  includeParentEnvironment: includeParentEnvironment,
);

/// Queues `data` for the process's stdin. False once the process is gone or its
/// stdin was closed.
Future<bool> processWriteStdin({
  required PlatformInt64 id,
  required List<int> data,
}) => RustLib.instance.api.crateApiProcessProcessWriteStdin(id: id, data: data);

/// Closes the process's stdin, which is what a child waiting on EOF needs.
Future<void> processCloseStdin({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiProcessProcessCloseStdin(id: id);

/// Kills the process. Reaches the direct child only, matching `Process.kill`.
Future<bool> processKill({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiProcessProcessKill(id: id);

class ProcessEvent {
  final ProcessEventKind kind;
  final PlatformInt64 sessionId;
  final int pid;
  final Uint8List data;
  final int exitCode;
  final String message;

  const ProcessEvent({
    required this.kind,
    required this.sessionId,
    required this.pid,
    required this.data,
    required this.exitCode,
    required this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sessionId.hashCode ^
      pid.hashCode ^
      data.hashCode ^
      exitCode.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          pid == other.pid &&
          data == other.data &&
          exitCode == other.exitCode &&
          message == other.message;
}

/// What a running process reported. `Started` always arrives first and carries
/// the session id the other calls take; output arrives as it is produced; `Exit`
/// and `Failure` are terminal and arrive once the output is drained.
enum ProcessEventKind { started, stdout, stderr, exit, failure }

class ProcessRunResult {
  final int exitCode;
  final String stdout;
  final String stderr;

  const ProcessRunResult({
    required this.exitCode,
    required this.stdout,
    required this.stderr,
  });

  @override
  int get hashCode => exitCode.hashCode ^ stdout.hashCode ^ stderr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessRunResult &&
          runtimeType == other.runtimeType &&
          exitCode == other.exitCode &&
          stdout == other.stdout &&
          stderr == other.stderr;
}
