// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'git.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`, `from`

Future<Uint8List> gitReadingDiffPatch({
  required String path,
  String? filePath,
  String? oldPath,
  GitChangeArea? area,
  String? commitOid,
  String? parentOid,
  String? baseRef,
}) => RustLib.instance.api.crateApiReadingDiffGitReadingDiffPatch(
  path: path,
  filePath: filePath,
  oldPath: oldPath,
  area: area,
  commitOid: commitOid,
  parentOid: parentOid,
  baseRef: baseRef,
);

Future<ReadingDiffPreparation> prepareReadingDiff({
  required List<int> diff,
  BigInt? maxChunkBytes,
}) => RustLib.instance.api.crateApiReadingDiffPrepareReadingDiff(
  diff: diff,
  maxChunkBytes: maxChunkBytes,
);

Future<ReadingDiffCompileResult> compileReadingDiffPlan({
  required List<int> diff,
  required List<int> sourceDiff,
  required String planJson,
}) => RustLib.instance.api.crateApiReadingDiffCompileReadingDiffPlan(
  diff: diff,
  sourceDiff: sourceDiff,
  planJson: planJson,
);

Future<ReadingDiffCompileResult> mergeReadingDiffChunks({
  required List<ReadingDiffCompiledChunk> chunks,
  required List<int> sourceDiff,
}) => RustLib.instance.api.crateApiReadingDiffMergeReadingDiffChunks(
  chunks: chunks,
  sourceDiff: sourceDiff,
);

class ReadingDiffChunk {
  final int index;
  final Uint8List rawDiff;
  final String numberedDiff;
  final Uint8List continuationPreamble;

  const ReadingDiffChunk({
    required this.index,
    required this.rawDiff,
    required this.numberedDiff,
    required this.continuationPreamble,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      rawDiff.hashCode ^
      numberedDiff.hashCode ^
      continuationPreamble.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingDiffChunk &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          rawDiff == other.rawDiff &&
          numberedDiff == other.numberedDiff &&
          continuationPreamble == other.continuationPreamble;
}

class ReadingDiffCompileResult {
  final Uint8List readingDiff;
  final String summary;
  final int changedLines;
  final int retainedChangedLines;

  const ReadingDiffCompileResult({
    required this.readingDiff,
    required this.summary,
    required this.changedLines,
    required this.retainedChangedLines,
  });

  @override
  int get hashCode =>
      readingDiff.hashCode ^
      summary.hashCode ^
      changedLines.hashCode ^
      retainedChangedLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingDiffCompileResult &&
          runtimeType == other.runtimeType &&
          readingDiff == other.readingDiff &&
          summary == other.summary &&
          changedLines == other.changedLines &&
          retainedChangedLines == other.retainedChangedLines;
}

class ReadingDiffCompiledChunk {
  final int index;
  final Uint8List continuationPreamble;
  final Uint8List readingDiff;
  final String summary;
  final int changedLines;
  final int retainedChangedLines;

  const ReadingDiffCompiledChunk({
    required this.index,
    required this.continuationPreamble,
    required this.readingDiff,
    required this.summary,
    required this.changedLines,
    required this.retainedChangedLines,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      continuationPreamble.hashCode ^
      readingDiff.hashCode ^
      summary.hashCode ^
      changedLines.hashCode ^
      retainedChangedLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingDiffCompiledChunk &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          continuationPreamble == other.continuationPreamble &&
          readingDiff == other.readingDiff &&
          summary == other.summary &&
          changedLines == other.changedLines &&
          retainedChangedLines == other.retainedChangedLines;
}

class ReadingDiffError implements FrbException {
  final String message;

  const ReadingDiffError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingDiffError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

class ReadingDiffPreparation {
  final BigInt rawBytes;
  final int schemaVersion;
  final String rubricVersion;
  final String planSchema;
  final List<ReadingDiffChunk> chunks;

  const ReadingDiffPreparation({
    required this.rawBytes,
    required this.schemaVersion,
    required this.rubricVersion,
    required this.planSchema,
    required this.chunks,
  });

  @override
  int get hashCode =>
      rawBytes.hashCode ^
      schemaVersion.hashCode ^
      rubricVersion.hashCode ^
      planSchema.hashCode ^
      chunks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingDiffPreparation &&
          runtimeType == other.runtimeType &&
          rawBytes == other.rawBytes &&
          schemaVersion == other.schemaVersion &&
          rubricVersion == other.rubricVersion &&
          planSchema == other.planSchema &&
          chunks == other.chunks;
}
