// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_searches`, `begin`, `from_io`, `new`, `prune_cancel_tombstones`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SearchCancellation`, `SearchEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<WorkspaceSearchResult> searchWorkspace({
  required WorkspaceSearchOptions options,
}) => RustLib.instance.api.crateApiWorkspaceSearchSearchWorkspace(
  options: options,
);

Future<WorkspaceSearchResult> searchWorkspaceCancelable({
  required WorkspaceSearchOptions options,
  required String requestId,
}) => RustLib.instance.api.crateApiWorkspaceSearchSearchWorkspaceCancelable(
  options: options,
  requestId: requestId,
);

Future<WorkspaceReplacePreview> previewWorkspaceReplace({
  required WorkspaceReplaceOptions options,
}) => RustLib.instance.api.crateApiWorkspaceSearchPreviewWorkspaceReplace(
  options: options,
);

Future<WorkspaceReplacePreview> previewWorkspaceReplaceCancelable({
  required WorkspaceReplaceOptions options,
  required String requestId,
}) => RustLib.instance.api
    .crateApiWorkspaceSearchPreviewWorkspaceReplaceCancelable(
      options: options,
      requestId: requestId,
    );

Future<WorkspaceReplaceResult> replaceWorkspaceMatches({
  required WorkspaceReplaceRequest request,
}) => RustLib.instance.api.crateApiWorkspaceSearchReplaceWorkspaceMatches(
  request: request,
);

Future<void> cancelWorkspaceSearch({required String requestId}) => RustLib
    .instance
    .api
    .crateApiWorkspaceSearchCancelWorkspaceSearch(requestId: requestId);

class WorkspaceReplaceConflict {
  final String relativePath;
  final String reason;

  const WorkspaceReplaceConflict({
    required this.relativePath,
    required this.reason,
  });

  @override
  int get hashCode => relativePath.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceReplaceConflict &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          reason == other.reason;
}

class WorkspaceReplaceFileExpectation {
  final String relativePath;
  final String contentToken;

  const WorkspaceReplaceFileExpectation({
    required this.relativePath,
    required this.contentToken,
  });

  @override
  int get hashCode => relativePath.hashCode ^ contentToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceReplaceFileExpectation &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          contentToken == other.contentToken;
}

class WorkspaceReplaceOptions {
  final WorkspaceSearchOptions search;
  final String replacement;
  final bool preserveCase;

  const WorkspaceReplaceOptions({
    required this.search,
    required this.replacement,
    required this.preserveCase,
  });

  @override
  int get hashCode =>
      search.hashCode ^ replacement.hashCode ^ preserveCase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceReplaceOptions &&
          runtimeType == other.runtimeType &&
          search == other.search &&
          replacement == other.replacement &&
          preserveCase == other.preserveCase;
}

class WorkspaceReplacePreview {
  final WorkspaceSearchResult result;
  final String replacement;
  final bool preserveCase;

  const WorkspaceReplacePreview({
    required this.result,
    required this.replacement,
    required this.preserveCase,
  });

  @override
  int get hashCode =>
      result.hashCode ^ replacement.hashCode ^ preserveCase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceReplacePreview &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          replacement == other.replacement &&
          preserveCase == other.preserveCase;
}

class WorkspaceReplaceRequest {
  final WorkspaceReplaceOptions options;
  final List<String> matchIds;
  final List<WorkspaceReplaceFileExpectation> expectedFiles;

  const WorkspaceReplaceRequest({
    required this.options,
    required this.matchIds,
    required this.expectedFiles,
  });

  @override
  int get hashCode =>
      options.hashCode ^ matchIds.hashCode ^ expectedFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceReplaceRequest &&
          runtimeType == other.runtimeType &&
          options == other.options &&
          matchIds == other.matchIds &&
          expectedFiles == other.expectedFiles;
}

class WorkspaceReplaceResult {
  final int filesChanged;
  final int matchesReplaced;
  final List<WorkspaceReplaceConflict> conflicts;

  const WorkspaceReplaceResult({
    required this.filesChanged,
    required this.matchesReplaced,
    required this.conflicts,
  });

  @override
  int get hashCode =>
      filesChanged.hashCode ^ matchesReplaced.hashCode ^ conflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceReplaceResult &&
          runtimeType == other.runtimeType &&
          filesChanged == other.filesChanged &&
          matchesReplaced == other.matchesReplaced &&
          conflicts == other.conflicts;
}

class WorkspaceSearchError implements FrbException {
  final WorkspaceSearchErrorKind kind;
  final String context;

  const WorkspaceSearchError({required this.kind, required this.context});

  @override
  int get hashCode => kind.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSearchError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          context == other.context;
}

enum WorkspaceSearchErrorKind {
  invalidPath,
  outsideWorkspace,
  invalidPattern,
  io,
  cancelled,
}

class WorkspaceSearchFileResult {
  final String relativePath;
  final String contentToken;
  final List<WorkspaceSearchMatch> matches;

  const WorkspaceSearchFileResult({
    required this.relativePath,
    required this.contentToken,
    required this.matches,
  });

  @override
  int get hashCode =>
      relativePath.hashCode ^ contentToken.hashCode ^ matches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSearchFileResult &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          contentToken == other.contentToken &&
          matches == other.matches;
}

class WorkspaceSearchMatch {
  final String id;
  final int line;
  final int column;
  final int matchLength;
  final String lineContent;
  final int? displayColumn;
  final int? displayMatchLength;
  final String? replacementPreview;

  const WorkspaceSearchMatch({
    required this.id,
    required this.line,
    required this.column,
    required this.matchLength,
    required this.lineContent,
    this.displayColumn,
    this.displayMatchLength,
    this.replacementPreview,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      line.hashCode ^
      column.hashCode ^
      matchLength.hashCode ^
      lineContent.hashCode ^
      displayColumn.hashCode ^
      displayMatchLength.hashCode ^
      replacementPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSearchMatch &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          line == other.line &&
          column == other.column &&
          matchLength == other.matchLength &&
          lineContent == other.lineContent &&
          displayColumn == other.displayColumn &&
          displayMatchLength == other.displayMatchLength &&
          replacementPreview == other.replacementPreview;
}

class WorkspaceSearchOptions {
  final String workspacePath;
  final String query;
  final bool caseSensitive;
  final bool wholeWord;
  final bool useRegex;
  final String? includePattern;
  final String? excludePattern;
  final bool includeIgnored;
  final int? maxResults;

  const WorkspaceSearchOptions({
    required this.workspacePath,
    required this.query,
    required this.caseSensitive,
    required this.wholeWord,
    required this.useRegex,
    this.includePattern,
    this.excludePattern,
    required this.includeIgnored,
    this.maxResults,
  });

  @override
  int get hashCode =>
      workspacePath.hashCode ^
      query.hashCode ^
      caseSensitive.hashCode ^
      wholeWord.hashCode ^
      useRegex.hashCode ^
      includePattern.hashCode ^
      excludePattern.hashCode ^
      includeIgnored.hashCode ^
      maxResults.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSearchOptions &&
          runtimeType == other.runtimeType &&
          workspacePath == other.workspacePath &&
          query == other.query &&
          caseSensitive == other.caseSensitive &&
          wholeWord == other.wholeWord &&
          useRegex == other.useRegex &&
          includePattern == other.includePattern &&
          excludePattern == other.excludePattern &&
          includeIgnored == other.includeIgnored &&
          maxResults == other.maxResults;
}

class WorkspaceSearchResult {
  final List<WorkspaceSearchFileResult> files;
  final int totalMatches;
  final bool truncated;

  const WorkspaceSearchResult({
    required this.files,
    required this.totalMatches,
    required this.truncated,
  });

  @override
  int get hashCode =>
      files.hashCode ^ totalMatches.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSearchResult &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          totalMatches == other.totalMatches &&
          truncated == other.truncated;
}
