// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Called only by the local desktop decision flow after explicit user action.
/// Neither the runtime RPC nor terminal CLI exposes a signing operation.
Future<Uint8List> signWorkflowDecision({
  required String runtimeDir,
  required String statementJson,
}) => RustLib.instance.api.crateApiWorkflowApprovalSignWorkflowDecision(
  runtimeDir: runtimeDir,
  statementJson: statementJson,
);
