part of 'alera_debug.dart';

final class _DebugContext {
  _DebugContext(this._options);

  final _Options _options;

  Future<int> buildCli() {
    return _run(_options.dartExecutable, <String>[
      'build',
      'cli',
      '--target',
      'bin/alera.dart',
      '--output',
      _options.bundleDir,
    ]);
  }

  Future<int> cliHelp() async {
    final buildExit = await buildCli();
    if (buildExit != 0) {
      return buildExit;
    }
    return _run(_cliExecutablePath, const <String>['--help']);
  }

  Future<int> hostDebug({required bool observe}) async {
    final paths = _runtimePaths;
    await paths.runtimeDir.create(recursive: true);
    if (await paths.controlFile.exists()) {
      await paths.controlFile.delete();
    }
    final arguments = <String>[
      if (observe) '--observe=${_options.debugPort}/127.0.0.1',
      'bin/alera.dart',
      'terminal-host',
      '--runtime-dir',
      paths.runtimeDir.path,
      '--control-file',
      paths.controlFile.path,
      '--token',
      _options.debugToken,
      '--empty-shutdown-delay-seconds',
      _options.hostEmptyShutdownSeconds,
      '--detached-session-shutdown-delay-seconds',
      _options.hostDetachedShutdownSeconds,
      '--scrollback-bytes',
      _options.hostScrollbackBytes,
    ];
    return _run(_options.dartExecutable, arguments, forwardStdin: true);
  }

  Future<int> buildHostDebugWrapper() async {
    final wrapper = File(_hostDebugWrapperPath);
    await wrapper.parent.create(recursive: true);
    return _run(_options.dartExecutable, <String>[
      'compile',
      'exe',
      _join('tool', 'debug', 'alera_debug_host_wrapper.dart'),
      '-o',
      wrapper.path,
    ]);
  }

  Future<int> appDebug() async {
    await _prepareFlavor();
    return _run(
      _options.flutterExecutable,
      _flutterRunArguments(),
      environment: _flutterEnvironment(),
      forwardStdin: true,
    );
  }

  Future<int> appDebugBundledCli() async {
    await _prepareFlavor();
    final buildExit = await buildCli();
    if (buildExit != 0) {
      return buildExit;
    }
    final environment = _flutterEnvironment();
    environment['ALERA_CLI_BUNDLE_DIR'] = _join(
      _repoRoot,
      _options.bundleDir,
      'bundle',
    );
    return _run(
      _options.flutterExecutable,
      _flutterRunArguments(),
      environment: environment,
      forwardStdin: true,
    );
  }

  Future<int> appDebugHostObserve() async {
    await _prepareFlavor();
    final wrapperExit = await buildHostDebugWrapper();
    if (wrapperExit != 0) {
      return wrapperExit;
    }
    final environment = _flutterEnvironment();
    environment['ALERA_CLI_PATH'] = _hostDebugWrapperPath;
    environment['ALERA_DEBUG_REPO_ROOT'] = _repoRoot;
    environment['ALERA_DEBUG_DART'] = _options.dartExecutable;
    environment['ALERA_CLI_DEBUG_PORT'] = _options.debugPort;
    return _run(
      _options.flutterExecutable,
      _flutterRunArguments(),
      environment: environment,
      forwardStdin: true,
    );
  }

  List<String> _flutterRunArguments() {
    return <String>[
      'run',
      '-d',
      _options.device,
      '--dart-define=ALERA_FLAVOR=${_options.flavor}',
    ];
  }

  Map<String, String> _flutterEnvironment() {
    final environment = Map<String, String>.of(Platform.environment);
    environment['ALERA_FLAVOR'] = _options.flavor;
    return environment;
  }

  Future<void> _prepareFlavor() async {
    if (!Platform.isMacOS) {
      return;
    }
    final configFile = File(
      _join(_repoRoot, 'macos', 'Runner', 'Configs', 'Flavor.xcconfig'),
    );
    final isRelease = _options.flavor == kAleraReleaseFlavor;
    final productName = isRelease ? kAleraReleaseAppName : kAleraDevAppName;
    final bundleId = isRelease ? kAleraReleaseBundleId : kAleraDevBundleId;
    final contents = <String>[
      '// Generated by tool/debug/alera_debug.dart for ALERA_FLAVOR=${_options.flavor}.',
      '// Do not edit by hand; regenerated on every build that goes through the makefile.',
      'ALERA_PRODUCT_NAME = $productName',
      'ALERA_BUNDLE_ID = $bundleId',
      '',
    ].join('\n');
    await configFile.parent.create(recursive: true);
    await configFile.writeAsString(contents);
  }

  Future<int> debugProcesses() async {
    final processes = await _listProcesses();
    final matches = processes.where(_isAleraProcess).toList();
    if (matches.isEmpty) {
      stdout.writeln('No Alera app or terminal-host processes found.');
    } else {
      for (final process in matches) {
        stdout.writeln('${process.pid} ${process.commandLine}');
      }
    }

    final controlFile = _runtimePaths.controlFile;
    if (await controlFile.exists()) {
      stdout.writeln('control file: ${controlFile.path}');
      stdout.writeln(await controlFile.readAsString());
    }
    return 0;
  }

  Future<int> hostStop() async {
    final controlFile = _runtimePaths.controlFile;
    if (!await controlFile.exists()) {
      stdout.writeln(
        'No terminal host control file found at ${controlFile.path}.',
      );
      return 0;
    }
    final decoded = jsonDecode(await controlFile.readAsString());
    if (decoded is! Map || decoded['pid'] is! int) {
      stderr.writeln('Terminal host control file does not contain a pid.');
      return 1;
    }
    final pid = decoded['pid'] as int;
    final stopped = Process.killPid(pid);
    await controlFile.delete();
    stdout.writeln(
      stopped
          ? 'Stopped terminal host pid $pid and removed ${controlFile.path}.'
          : 'Terminal host pid $pid was not running; removed stale ${controlFile.path}.',
    );
    return 0;
  }

  bool _isAleraProcess(_ProcessInfo process) {
    final commandLine = process.commandLine;
    final normalized = _normalizeSeparators(commandLine);
    return commandLine.contains('alera terminal-host') ||
        normalized.contains('/alera/bin/alera') ||
        normalized.contains('/.dart_tool/alera/bundle/bin/alera') ||
        normalized.contains('/Alera.app/Contents/MacOS/Alera') ||
        normalized.contains('/Alera Dev.app/Contents/MacOS/Alera Dev') ||
        normalized.contains('/alera-dev') ||
        normalized.endsWith('alera-dev') ||
        normalized.endsWith('alera-dev.exe');
  }

  _RuntimePaths get _runtimePaths {
    final supportDir =
        _options.appSupportDir ?? _defaultAppSupportDir(_options.appId);
    final runtimeDir = Directory(_join(supportDir, 'terminal_host'));
    return _RuntimePaths(
      runtimeDir: runtimeDir,
      controlFile: File(_join(runtimeDir.path, 'host.json')),
    );
  }

  String get _cliExecutablePath {
    return _join(
      _repoRoot,
      _options.bundleDir,
      'bundle',
      'bin',
      Platform.isWindows ? 'alera.exe' : 'alera',
    );
  }

  String get _hostDebugWrapperPath {
    return _join(
      _repoRoot,
      '.dart_tool',
      Platform.isWindows ? 'alera-debug-host.exe' : 'alera-debug-host',
    );
  }
}
