//! Flavor identity strings. Keep these identical to
//! `lib/src/core/build_flavor.dart` so `Flavor.xcconfig` cannot drift from the
//! Dart compile-time constants.

pub const RELEASE_FLAVOR: &str = "release";
pub const DEV_FLAVOR: &str = "dev";
pub const RELEASE_APP_NAME: &str = "Alera";
pub const DEV_APP_NAME: &str = "Alera Dev";
pub const RELEASE_BUNDLE_ID: &str = "dev.leynier.alera";
pub const DEV_BUNDLE_ID: &str = "dev.leynier.alera.dev";

pub fn app_name(flavor: &str) -> &'static str {
    if flavor == RELEASE_FLAVOR {
        RELEASE_APP_NAME
    } else {
        DEV_APP_NAME
    }
}

pub fn bundle_id(flavor: &str) -> &'static str {
    if flavor == RELEASE_FLAVOR {
        RELEASE_BUNDLE_ID
    } else {
        DEV_BUNDLE_ID
    }
}

pub fn flavor_xcconfig(flavor: &str) -> String {
    format!(
        "// Generated by alera-xtask for ALERA_FLAVOR={flavor}.\n\
         // Do not edit by hand; regenerated on every build that goes through the makefile.\n\
         ALERA_PRODUCT_NAME = {product_name}\n\
         ALERA_BUNDLE_ID = {bundle_id}\n",
        product_name = app_name(flavor),
        bundle_id = bundle_id(flavor),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;

    fn dart_build_flavor_source() -> String {
        let path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../lib/src/core/build_flavor.dart");
        fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!("read {}: {error}", path.display());
        })
    }

    #[test]
    fn constants_match_dart_build_flavor() {
        let source = dart_build_flavor_source();
        for (name, value) in [
            ("kAleraReleaseFlavor", RELEASE_FLAVOR),
            ("kAleraDevFlavor", DEV_FLAVOR),
            ("kAleraReleaseAppName", RELEASE_APP_NAME),
            ("kAleraDevAppName", DEV_APP_NAME),
            ("kAleraReleaseBundleId", RELEASE_BUNDLE_ID),
            ("kAleraDevBundleId", DEV_BUNDLE_ID),
        ] {
            let expected = format!("const String {name} = '{value}';");
            assert!(
                source.contains(&expected),
                "missing `{expected}` in lib/src/core/build_flavor.dart"
            );
        }
    }

    #[test]
    fn xcconfig_uses_dev_identity_by_default() {
        let rendered = flavor_xcconfig(DEV_FLAVOR);
        assert!(rendered.contains("ALERA_PRODUCT_NAME = Alera Dev"));
        assert!(rendered.contains("ALERA_BUNDLE_ID = dev.leynier.alera.dev"));
        assert!(rendered.contains("alera-xtask"));
    }
}
